"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JAVA_SCALAR_MAP = {
    ID: 'String',
    String: 'String',
    Int: 'Integer',
    Float: 'Float',
    Boolean: 'Boolean',
    AWSDate: 'java.util.Date',
    AWSDateTime: 'java.util.Date',
    AWSTime: 'java.sql.Time',
    AWSTimestamp: 'long',
    AWSEmail: 'String',
    AWSJSON: 'String',
    AWSURL: 'String',
    AWSPhone: 'String',
    AWSIPAddress: 'String',
};
exports.SWIFT_SCALAR_MAP = {
    ID: 'String',
    String: 'String',
    Int: 'Int',
    Float: 'Double',
    Boolean: 'Bool',
    AWSDate: 'Date',
    AWSTime: 'Date',
    AWSDateTime: 'Date',
    AWSTimestamp: 'Int',
    AWSEmail: 'String',
    AWSJSON: 'String',
    AWSURL: 'String',
    AWSPhone: 'String',
    AWSIPAddress: 'String',
};
exports.TYPESCRIPT_SCALAR_MAP = {
    ID: 'string',
    String: 'string',
    Int: 'number',
    Float: 'number',
    Boolean: 'boolean',
    AWSDate: 'string',
    AWSDateTime: 'string',
    AWSTime: 'string',
    AWSTimestamp: 'number',
    AWSEmail: 'string',
    AWSJSON: 'string',
    AWSURL: 'string',
    AWSPhone: 'string',
    AWSIPAddress: 'string',
};
exports.METADATA_SCALAR_MAP = {
    ID: 'ID',
    Boolean: 'Boolean',
    String: 'String',
    AWSDate: 'AWSDate',
    AWSTime: 'AWSTime',
    AWSDateTime: 'AWSDateTime',
    AWSEmail: 'AWSEmail',
    AWSJSON: 'AWSJSON',
    AWSURL: 'AWSURL',
    AWSPhone: 'AWSPhone',
    AWSIPAddress: 'AWSIPAddress',
    Int: 'Int',
    Float: 'Float',
    AWSTimestamp: 'AWSTimestamp',
};
//# sourceMappingURL=index.js.map